// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911055849_RevertCreatedAtToTimestamptz")]
    partial class RevertCreatedAtToTimestamptz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Models.Domain.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("src.Models.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "StartTime", "EndTime");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("src.Models.Domain.BookingAmenity", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BookingId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("BookingAmenities");
                });

            modelBuilder.Entity("src.Models.Domain.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("src.Models.Domain.HallAmenity", b =>
                {
                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("HallId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("HallAmenities");
                });

            modelBuilder.Entity("src.Models.Domain.Booking", b =>
                {
                    b.HasOne("src.Models.Domain.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("src.Models.Domain.BookingAmenity", b =>
                {
                    b.HasOne("src.Models.Domain.Amenity", "Amenity")
                        .WithMany("BookingAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("src.Models.Domain.Booking", "Booking")
                        .WithMany("BookingAmenities")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("src.Models.Domain.HallAmenity", b =>
                {
                    b.HasOne("src.Models.Domain.Amenity", "Amenity")
                        .WithMany("HallAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.Domain.Hall", "Hall")
                        .WithMany("HallAmenities")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("src.Models.Domain.Amenity", b =>
                {
                    b.Navigation("BookingAmenities");

                    b.Navigation("HallAmenities");
                });

            modelBuilder.Entity("src.Models.Domain.Booking", b =>
                {
                    b.Navigation("BookingAmenities");
                });

            modelBuilder.Entity("src.Models.Domain.Hall", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("HallAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
